/********************************************************************
* ../src/SpmsRowDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/SpmsRowDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSpmsRowDict();
extern void G__cpp_setup_inheritanceSpmsRowDict();
extern void G__cpp_setup_typetableSpmsRowDict();
extern void G__cpp_setup_memvarSpmsRowDict();
extern void G__cpp_setup_globalSpmsRowDict();
extern void G__cpp_setup_memfuncSpmsRowDict();
extern void G__cpp_setup_funcSpmsRowDict();
extern void G__set_cpp_environmentSpmsRowDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SpmsRow.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SpmsRowDictLN_TClass;
extern G__linked_taginfo G__SpmsRowDictLN_TBuffer;
extern G__linked_taginfo G__SpmsRowDictLN_TMemberInspector;
extern G__linked_taginfo G__SpmsRowDictLN_TObject;
extern G__linked_taginfo G__SpmsRowDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SpmsRowDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SpmsRowDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SpmsRowDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SpmsRowDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SpmsRowDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__SpmsRowDictLN_DBITableRow;
extern G__linked_taginfo G__SpmsRowDictLN_SpmsRow;

/* STUB derived class for protected member access */
