#!/bin/bash

export JUNOTOP=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc1120/Pre-Release/J23.1.0-rc2/
export WORKTOP=/junofs/users/yuchincheng/J23.1.0-rc2
export JUNO_OFFLINE_OFF=1   # disable official offline before source setup.sh


pushd $JUNOTOP >& /dev/null
source setup.sh
popd >& /dev/null

pushd $WORKTOP >& /dev/null
if [ -f "junosw/InstallArea/setup.sh" ]; then
    echo 'Setup Local JUNOSW (CMake version)'
    pushd junosw/InstallArea >& /dev/null
    source setup.sh
    popd >& /dev/null
fi
popd >& /dev/null
